id: P38AB5775
initial_creation_type: input
source_metadata:
  Title: तत्त्वज्ञानसंसिद्धि-महासुखरकाशिका-टीका
  Editor: '-'
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  तत्त्वज्ञानसंसिद्धि-महासुखरकाशिका-टीका:
    Text Version: Devanagari
    Input Personnel: Bibek Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:18:30.357849'
last_modified_at: '2022-03-08T17:18:30.357857'
